### PR TITLE
SDX-1256 Open dropdown up when not enough space

### PR DESCRIPTION
**Pull request by olga-andreeva**

### CODE REVIEW

**Comment by olga-andreeva** [comment]
I'm also not sure how to test this.

**Comment by ahollesen** [comment]
PR for SDX still needed for `z-index` (sort of as you had it)

**Comment by muthan** [comment]
If no one knows how to test this. This is fine for me.

**Comment by olga-andreeva** [comment]
Follow-up buyer-tools PR: https://github.com/SmaatoUI/buyer-tools/pull/443

**Pull request merged**
